services:
  mongodb:
    image: mongo:6
    container_name: contoso-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  contoso-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contoso-backend
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017
      ELASTICSEARCH_URL: http://host.docker.internal:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      # Add any backend secrets here as needed
    ports:
      - "8080:8080"

volumes:
  mongo_data:
  es_data:
