version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: contoso-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  contoso-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contoso-backend
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/contoso
      ELASTICSEARCH_URL: http://host.docker.internal:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      # Add any backend secrets here as needed
    ports:
      - "8080:8080"

  contoso-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: contoso-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  contoso-kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: contoso-kibana
    depends_on:
      - contoso-elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://contoso-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"

volumes:
  mongo_data:
  es_data:
